version: '3'

networks:
  happy:
    driver: bridge

services:
  postgres:
    image: 'postgres'
    networks:
      - happy
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=happy
    ports:
      - '5432:5432'
  api:
    build: .
    depends_on:
      - postgres
    networks:
      - happy
    environment:
      - PORT=3333
    ports:
      - '3333:3333'
    entrypoint: yarn dev
